Repository chas-academy/u02-redesign-fulhackarna, pull requests merged in 2020-11, with the labels that each got.

#30 Fix paths to global header and footer styles
  assets/styles/_footer.scss
  assets/styles/_header.scss
  kontakt/style.css
  kontakt/style.css.map
  kontakt/style.scss
  nyhetsrum/_footer.scss
  nyhetsrum/_header.scss
  nyhetsrum/style.css
  nyhetsrum/style.css.map
  nyhetsrum/style.scss
  om-oss/_footer.scss
  om-oss/_header.scss
  om-oss/style.css
  om-oss/style.css.map
  om-oss/style.scss
  publikationer/_footer.scss
  publikationer/_header.scss
  publikationer/style.css
  publikationer/style.css.map
  publikationer/style.scss
  regelverk/_footer.scss
  regelverk/_header.scss
  regelverk/style.css
  regelverk/style.css.map
  regelverk/style.scss
  sok-pa-myh/_footer.scss
  sok-pa-myh/_header.scss
  sok-pa-myh/main.css
  sok-pa-myh/main.css.map
  sok-pa-myh/main.scss
  statistik/_footer.scss
  statistik/_header.scss
  statistik/style.css
  statistik/style.css.map
  statistik/style.scss
Labels: enhancement

#32 Fix Validation errors and redesign of header
  assets/javascript/nav.js
  assets/styles/_header.scss
  kontakt/index.html
  kontakt/style.css
  kontakt/style.css.map
  nyhetsrum/index.html
  nyhetsrum/style.css
  nyhetsrum/style.css.map
  nyhetsrum/style.scss
  om-oss/index.html
  om-oss/style.css
  om-oss/style.css.map
  om-oss/style.scss
  publikationer/index.html
  publikationer/style.css
  publikationer/style.css.map
  publikationer/style.scss
  regelverk/index.html
  regelverk/style.css
  regelverk/style.css.map
  sok-pa-myh/main.css
  sok-pa-myh/main.css.map
  sok-pa-myh/main.scss
  sok-pa-myh/sok.html
  statistik/index.html
  statistik/style.css
  statistik/style.css.map
Labels: bug, enhancement

#33 Add contact form and video
  kontakt/index.html
  kontakt/style.css
  kontakt/style.css.map
  kontakt/style.scss
Labels: enhancement

#36 fix(footer): fix code regression
  assets/javascript/footer.js
  assets/styles/_footer.scss
  kontakt/index.html
  kontakt/style.css
  kontakt/style.css.map
  kontakt/style.scss
  nyhetsrum/index.html
  nyhetsrum/style.css
  nyhetsrum/style.css.map
  nyhetsrum/style.scss
  om-oss/index.html
  om-oss/style.css
  om-oss/style.css.map
  om-oss/style.scss
  publikationer/index.html
  publikationer/style.css
  publikationer/style.css.map
  publikationer/style.scss
  regelverk/index.html
  regelverk/style.css
  regelverk/style.css.map
  regelverk/style.scss
  sok-pa-myh/main.css
  sok-pa-myh/main.css.map
  sok-pa-myh/main.scss
  sok-pa-myh/sok.html
  statistik/index.html
  statistik/style.css
  statistik/style.css.map
  statistik/style.scss
Labels: bug
